const greetings = [
  "Howdy, partner!",
  "Greetings and salutations!",
  "Well, hello there, sunshine!",
  "What's the good word?",
  "Hey, superstar!",
  "Hola, amigo!",
  "Hello, you magnificent creature!",
  "Hey there, champ!",
  "Hiya, hotshot!",
  "Bonjour, mon ami!",
  "Good to see you, you glorious human!",
  "Hello, you marvelous being!",
  "What's cookin', good lookin'?",
  "How's it hanging?",
  "Hey, you beautiful soul!",
  "Greetings, earthling!",
  "How's it shakin', bacon?",
  "Ahoy there!",
  "Greetings, starfighter!",
  "What's poppin'?",
  "Hey, wizard!",
  "Hey there, buckaroo!",
  "Howdy do, kangaroo!",
  "Good morrow, kind soul!",
  "Hello, brave knight!",
  "Greetings, fellow traveler!",
]

export default greetings
